#!/bin/sh

case "$1" in
    has_param)
	echo yes
	exit 0
	;;
    set)

	if [ x"$2" = xon ]; then
            OPTION="--enable-polling"
        else
            OPTION=""
        fi
        for i in /dev/cdrom*; do
            if [ -b "$i" ]; then
                hal-disable-polling --device "$i" $OPTION
            fi
        done
	exit 0
	;;
    any_param)
	echo no
	exit 0
	;;
    avail_params)
	echo -ne "on\noff\n"
	exit 0
	;;
esac
