#!/bin/sh

case "$1" in
    has_param)
	echo yes
	exit 0
	;;
    set)
	echo "$2"00 > /proc/sys/vm/dirty_writeback_centisecs
	exit 0
	;;
    any_param)
	echo no
	exit 0
	;;
    avail_params)
	echo -ne "1\n5\n10\n50\n100\n200\n300\n400\n500\n"
	exit 0
	;;
esac
