#!/bin/sh

case "$1" in
    has_param)
	echo yes
	exit 0
	;;
    set)
	if [ x"$2" = xon ]; then
            echo 1 > /sys/devices/platform/acer-wmi/wireless
        else
            echo 0 > /sys/devices/platform/acer-wmi/wireless
        fi
	exit 0
	;;
    any_param)
	echo no
	exit 0
	;;
    avail_params)
	echo -ne "on\noff\n"
	exit 0
	;;
esac

